// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uftrV6ZeR5SuVi5gnDLzFk
// Component: If1fqS83W9Lw
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  get as $stateGet,
  hasVariant,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Header from "../../Header"; // plasmic-import: fDzUbLUclsbT/component
import Checkbox from "../../Checkbox"; // plasmic-import: 9vVSXaKyPA3c/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: uftrV6ZeR5SuVi5gnDLzFk/projectcss
import sty from "./PlasmicUser.module.css"; // plasmic-import: If1fqS83W9Lw/css
import ArrowSvgIcon from "./icons/PlasmicIcon__ArrowSvg"; // plasmic-import: ZrG95_rSrl_o/icon
import dynamic from "next/dynamic";
import "leaflet/dist/leaflet.css";

const MapComponent = dynamic(() => import("../../MapComponent"), { ssr: false });

createPlasmicElementProxy;

export const PlasmicUser__VariantProps = new Array(
  "sidebarOpen",
  "sidebarClose"
);

export const PlasmicUser__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUser__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const [selectingStart, setSelectingStart] = React.useState(false); //Controls whether the user is selecting a starting point
  const [startPoint, setStartPoint] = React.useState(null); // Stores the user-selected starting point
  const [computeAccessibility, setComputeAccessibility] = React.useState(false);
  const [walkingTime, setWalkingTime] = React.useState(15); // Default walking time is 15 minutes
  const [walkingSpeed, setWalkingSpeed] = React.useState(5); // Default walking speed is 5 km/h
  const [selectedLayers, setSelectedLayers] = React.useState([]); // load Layer
  const [layerValues, setLayerValues] = React.useState({}); //store input variable value by user

  // slidebar categorys
  const [openCategory, setOpenCategory] = React.useState(null); // Opened variable category
  const [showInfo, setShowInfo] = React.useState(false); // Show the info box about variables

  const toggleCategory = (category) => {
    setOpenCategory(openCategory === category ? null : category);
  };

  const [resetTrigger, setResetTrigger] = React.useState(false);

  const handleResetResults = () => {
    console.log("🚀 Resetting accessibility results...");
    setComputeAccessibility(false); // Ensure calculation is stopped
    setStartPoint(null); // Clear selected start point
    setResetTrigger(true);
  };

  const onResetHandled = () => {
    console.log("父组件：子组件那边重置完了");
    setResetTrigger(false);
  };

  // const toggleLayer = (layer) => {
  //   setSelectedLayers((prev) =>
  //     prev.includes(layer) ? prev.filter((l) => l !== layer) : [...prev, layer]
  //   );
  // };
  const toggleLayer = (layer) => {
    setSelectedLayers((prev) => {
        const newLayers = prev.includes(layer) 
            ? prev.filter(l => l !== layer) 
            : [...prev, layer];
        
        // 仅在新增layer时初始化值
        if (!prev.includes(layer)) {
            setLayerValues(prevValues => ({
                ...prevValues,
                [layer]: prevValues[layer] || 1.0
            }));
        }
        return newLayers;
    });
  };

  //handle input variable values
  // const handleInputChange = (event, layer) => {
  //   const value = parseFloat(event.target.value);
  //   setLayerValues(prev => ({
  //     ...prev,
  //     [layer]: value  // ✅ 存储每个变量的输入值
  //   }));
  // };  
  const handleInputChange = (event, layer) => {
    const value = parseFloat(event.target.value);
    // 如果输入无效，保留上一次有效值或设为默认值 1.0
    setLayerValues(prev => ({
      ...prev,
      [layer]: isNaN(value) ? (prev[layer] || 1.0) : value
    }));
    console.log("Updated layerValues:", { ...layerValues, [layer]: value });
  };

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "sidebarOpen",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.sidebarOpen
      },
      {
        path: "sidebarClose",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.sidebarClose
      },
      {
        path: "checkboxLight.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "checkboxTactilePav.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "checkboxCrossing.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "checkboxPoi.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "checkboxNoise.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "checkboxTree.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "checkboxOriginal.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "selectedLayers",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => []
      },
      {
        path: "selectingStart",  // Add selection mode variable
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root,
            {
              [sty.rootsidebarClose]: hasVariant(
                $state,
                "sidebarClose",
                "sidebarClose"
              ),
              [sty.rootsidebarOpen]: hasVariant(
                $state,
                "sidebarOpen",
                "sidebarOpen"
              )
            }
          )}
        >

          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"mapBox"}
            data-plasmic-override={overrides.mapBox}
            className={classNames(projectcss.all, sty.mapBox, {
              [sty.mapBoxsidebarOpen]: hasVariant(
                $state,
                "sidebarOpen",
                "sidebarOpen"
              )
            })}
            id={"map"}
          >
            <MapComponent 
              selectedLayers={selectedLayers} 
              selectingStart={selectingStart} 
              setSelectingStart={setSelectingStart}
              walkingTime={walkingTime} 
              walkingSpeed={walkingSpeed} 
              startPoint={startPoint} // Transfer starting point
              setStartPoint={setStartPoint} // Allow MapComponent to modify the starting point
              computeAccessibility={computeAccessibility} // Trigger calculation
              setComputeAccessibility={setComputeAccessibility} // Reset after calculation
              resetTrigger={resetTrigger}
              onResetHandled={onResetHandled}
              layerValues={layerValues}
            />
          </div>

          <div
            data-plasmic-name={"sideBarBox"}
            data-plasmic-override={overrides.sideBarBox}
            className={classNames(projectcss.all, sty.sideBarBox, {
              [sty.sideBarBoxsidebarClose]: hasVariant(
                $state,
                "sidebarClose",
                "sidebarClose"
              ),
              [sty.sideBarBoxsidebarOpen]: hasVariant(
                $state,
                "sidebarOpen",
                "sidebarOpen"
              )
            })}
          >
            <ArrowSvgIcon
              className={classNames(projectcss.all, sty.svg__lhwYj, {
                [sty.svgsidebarClose__lhwYj3FoUt]: hasVariant(
                  $state,
                  "sidebarClose",
                  "sidebarClose"
                ),
                [sty.svgsidebarOpen__lhwYJyaBs4]: hasVariant(
                  $state,
                  "sidebarOpen",
                  "sidebarOpen"
                )
              })}
              onClick={async event => {
                const $steps = {};
                $steps["updateSidebarClose"] = true
                  ? (() => {
                      const actionArgs = {
                        vgroup: "sidebarClose",
                        operation: 2
                      };
                      return (({ vgroup, value }) => {
                        if (typeof value === "string") {
                          value = [value];
                        }
                        const oldValue = $stateGet($state, vgroup);
                        $stateSet($state, vgroup, !oldValue);
                        return !oldValue;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateSidebarClose"] != null &&
                  typeof $steps["updateSidebarClose"] === "object" &&
                  typeof $steps["updateSidebarClose"].then === "function"
                ) {
                  $steps["updateSidebarClose"] = await $steps[
                    "updateSidebarClose"
                  ];
                }
              }}
              role={"img"}
            />

            <ArrowSvgIcon
              className={classNames(projectcss.all, sty.svg___9Ata1, {
                [sty.svgsidebarOpen___9Ata1YaBs4]: hasVariant(
                  $state,
                  "sidebarOpen",
                  "sidebarOpen"
                )
              })}
              onClick={async event => {
                const $steps = {};
                $steps["updateSidebarClose"] = true
                  ? (() => {
                      const actionArgs = {
                        vgroup: "sidebarClose",
                        operation: 2
                      };
                      return (({ vgroup, value }) => {
                        if (typeof value === "string") {
                          value = [value];
                        }
                        const oldValue = $stateGet($state, vgroup);
                        $stateSet($state, vgroup, !oldValue);
                        return !oldValue;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateSidebarClose"] != null &&
                  typeof $steps["updateSidebarClose"] === "object" &&
                  typeof $steps["updateSidebarClose"].then === "function"
                ) {
                  $steps["updateSidebarClose"] = await $steps[
                    "updateSidebarClose"
                  ];
                }
              }}
              role={"img"}
            />

            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox, {
                [sty.freeBoxsidebarOpen]: hasVariant(
                  $state,
                  "sidebarOpen",
                  "sidebarOpen"
                )
              })}
            > 

              {/*  User Setting Section */}
              <div className={sty["sidebar-section"]}>
                <h3 className={sty["sidebar-title"]}>User Setting</h3>
                {/* Walking Time */}
                <div className={sty["sidebar-text-bold"]}>
                  Walking Time <span className={sty["sidebar-text"]}>({walkingTime} minutes)</span>
                </div>
                <div className={sty["sidebar-slider"]}>
                    <input
                      type="range"
                      min="1"
                      max="60"
                      step="1"
                      value={walkingTime}
                      onChange={(e) => setWalkingTime(Number(e.target.value))}
                      className={sty["input"]}
                    />
                </div>
                {/* Walking Speed */}
                <div className={sty["sidebar-text-bold"]}>
                  Walking Speed <span className={sty["sidebar-text"]}>({walkingSpeed} km/h)</span>
                </div>
                <div className={sty["sidebar-slider"]}>
                    <input
                      type="range"
                      min="1"
                      max="8"
                      step="0.1"
                      value={walkingSpeed}
                      onChange={(e) => setWalkingSpeed(Number(e.target.value))}
                      className={sty["input"]}
                    />
                </div>

                {/* Add a "Select starting point" button here */}
                <div className={sty["button-container"]}>
                  <button 
                    onClick={() => setSelectingStart(true)}
                    className={sty["setup-button"]}
                  >
                    <img 
                      src="https://cdn-icons-png.flaticon.com/512/684/684908.png" 
                      alt="Location Icon"
                      className={sty["img"]} 
                    />
                    <span className={sty["sidebar-text-bold"]}>Select Start Point</span>
                  </button>
                </div>
                <div className={sty["button-container"]}>
                  {/* button for accessibility computation */}
                  <div className={sty["button-container"]}>
                    <button
                      onClick={() => {
                        if (!startPoint) {
                          alert("Please select a starting point first!");
                          return;
                        }
                        setComputeAccessibility(true);
                      }}
                      className={sty["setup-button"]}
                    >
                      <span className={sty["sidebar-text-bold"]}>Get Attachment Area</span>
                    </button>

                    <button
                      onClick={handleResetResults}
                      className={sty["setup-button"]}
                    >
                      <span className={sty["sidebar-text-bold"]}>Reset</span>
                    </button>
                  </div>
                </div>
              </div>

              {/* 🟢 Analysis Variables */}
              <div className={sty["sidebar-section"]}>
                <div className={sty["title-container"]}>
                  <h3 className={sty["sidebar-title"]}>Variable</h3>
                  {/* info icon，click to show tooltip */}
                  <span
                    className={sty["info-icon"]}
                    onClick={() => setShowInfo(!showInfo)}
                  >
                    i
                  </span>
                  {/* tooltip*/}
                  <div className={`${sty["tooltip"]} ${showInfo ? sty["show"] : ""}`}>
                    <p>Select variables and set the speed penalty between 0 and 1:</p>
                    <ul>
                      <p><strong>0</strong>: Completely inaccessible</p>
                      <p><strong>1</strong>: Fully comfortable</p>
                      <p>Lower values = Greater barrier</p>
                    </ul>
                  </div>
                </div>

                <div className={sty["faq-container"]}>
                  <div className={sty["faq-answer"]}>
                    {/* Default value without variables */}
                    <div className={sty["checkbox-container"]}>
                      <label className={sty["checkbox-label"]}>
                        <input type="checkbox" onChange={() => toggleLayer("original")} />
                        <span className={sty["sidebar-text"]}>Default</span>
                      </label>
                    </div>
                  </div> 
                  {/* Infrastructure */}
                  <div className={sty["faq-item"]}>
                    <button className={sty["faq-question"]} onClick={() => toggleCategory("infra")}>
                      <span className={sty["sidebar-subtitle"]}>Infrastructure</span>
                      <span className={sty["faq-icon"]}>{openCategory === "infra" ? "−" : "+"}</span>
                    </button>
                    {openCategory === "infra" && (
                      <div className={sty["faq-answer"]}>
                        {/* Light Weight Setting */}
                        <div className={sty["checkbox-container"]}>
                          <label className={sty["checkbox-label"]}>
                            <input type="checkbox" onChange={() => toggleLayer("light")} />
                            <span className={sty["sidebar-text"]}>Light</span>
                          </label>
                          <input type="number" className={sty["checkbox-input"]} 
                            placeholder="0 - 1"  
                            min="0" 
                            max="1" 
                            step="0.1"
                            value={layerValues["light"] ?? ""}  // ✅ 绑定 layerValues
                            onChange={(event) => handleInputChange(event, "light")}  // ✅ 监听输入
                          />
                        </div>
                        {/* Tactile Pavement Weight Setting */}
                        <div className={sty["checkbox-container"]}>
                          <label className={sty["checkbox-label"]}>
                            <input type="checkbox" onChange={() => toggleLayer("tactile_pavement")} />
                            <span className={sty["sidebar-text"]}>Tactile Pavement</span>
                          </label>
                          <input type="number" className={sty["checkbox-input"]} 
                            placeholder="0 - 1"  
                            min="0" 
                            max="1" 
                            step="0.1"
                            value={layerValues["tactile_pavement"] || ""}  // ✅ 绑定 layerValues
                            onChange={(event) => handleInputChange(event, "tactile_pavement")}  // ✅ 监听输入
                          />
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Environmental Factors */}
                  <div className={sty["faq-item"]}>
                    <button className={sty["faq-question"]} onClick={() => toggleCategory("env")}>
                      <span className={sty["sidebar-subtitle"]}>Environmental Factors</span>
                      <span className={sty["faq-icon"]}>{openCategory === "env" ? "−" : "+"}</span>
                    </button>
                    {openCategory === "env" && (
                      <div className={sty["faq-answer"]}>
                        {/* Street Crossing Weight Setting */}
                        <div className={sty["checkbox-container"]}>
                          <label className={sty["checkbox-label"]}>
                            <input type="checkbox" onChange={() => toggleLayer("crossing")} />
                            <span className={sty["sidebar-text"]}>Street Crossing</span>
                          </label>
                          <input type="number" className={sty["checkbox-input"]} 
                            placeholder="0 - 1"  
                            min="0" 
                            max="1" 
                            step="0.1"
                            value={layerValues["crossing"] || ""}  // ✅ 绑定 layerValues
                            onChange={(event) => handleInputChange(event, "crossing")}  // ✅ 监听输入
                          />
                        </div>
                        {/* Noise Weight Setting */}
                        <div className={sty["checkbox-container"]}>
                          <label className={sty["checkbox-label"]}>
                            <input type="checkbox" onChange={() => toggleLayer("noise")} />
                            <span className={sty["sidebar-text"]}>Noise</span>
                          </label>
                          <input type="number" className={sty["checkbox-input"]} 
                            placeholder="0 - 1"  
                            min="0" 
                            max="1" 
                            step="0.1"
                            value={layerValues["noise"] || ""}  // ✅ 绑定 layerValues
                            onChange={(event) => handleInputChange(event, "noise")}  // ✅ 监听输入
                          />
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Vegetation */}
                  <div className={sty["faq-item"]}>
                    <button className={sty["faq-question"]} onClick={() => toggleCategory("veg")}>
                      <span className={sty["sidebar-subtitle"]}>Vegetation</span>
                      <span className={sty["faq-icon"]}>{openCategory === "veg" ? "−" : "+"}</span>
                    </button>
                    {openCategory === "veg" && (
                      <div className={sty["faq-answer"]}>
                        {/* Trees Weight Setting */}
                        <div className={sty["checkbox-container"]}>
                          <label className={sty["checkbox-label"]}>
                            <input type="checkbox" onChange={() => toggleLayer("tree")} />
                            <span className={sty["sidebar-text"]}>Trees</span>
                          </label>
                          <input type="number" className={sty["checkbox-input"]} 
                            placeholder="0 - 1"  
                            min="0" 
                            max="1" 
                            step="0.1"
                            value={layerValues["tree"] || ""}  // ✅ 绑定 layerValues
                            onChange={(event) => handleInputChange(event, "tree")}  // ✅ 监听输入
                          />
                        </div>
                      </div>
                    )}
                  </div>

                </div>
              </div>

              {/* Load Layers */}
              <div className={sty["sidebar-section"]}>
                <h3 className={sty["sidebar-title"]}>Map Layers</h3>
                <label>
                  <input 
                    type="checkbox" 
                    checked={selectedLayers.includes("roads")} 
                    onChange={() => toggleLayer("roads")} 
                  /> Roads
                </label>
              </div>

            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "mapBox",
    "sideBarBox",
    "freeBox",
    "checkboxLight",
    "checkboxTactilePav",
    "checkboxCrossing",
    "checkboxPoi",
    "checkboxNoise",
    "checkboxTree",
    "checkboxOriginal"
  ],

  header: ["header"],
  mapBox: ["mapBox"],
  sideBarBox: [
    "sideBarBox",
    "freeBox",
    "checkboxLight",
    "checkboxTactilePav",
    "checkboxCrossing",
    "checkboxPoi",
    "checkboxNoise",
    "checkboxTree",
    "checkboxOriginal",
  ],

  freeBox: [
    "freeBox",
    "checkboxLight",
    "checkboxTactilePav",
    "checkboxCrossing",
    "checkboxPoi",
    "checkboxNoise",
    "checkboxTree",
    "checkboxOriginal",
  ],

  checkboxLight: ["checkboxLight"],
  checkboxTactilePav: ["checkboxTactilePav"],
  checkboxCrossing: ["checkboxCrossing"],
  checkboxPoi: ["checkboxPoi"],
  checkboxNoise: ["checkboxNoise"],
  checkboxTree: ["checkboxTree"],
  checkboxOriginal: ["checkboxOriginal"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUser__ArgProps,
          internalVariantPropNames: PlasmicUser__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUser__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUser";
  } else {
    func.displayName = `PlasmicUser.${nodeName}`;
  }
  return func;
}

export const PlasmicUser = Object.assign(
  // Top-level PlasmicUser renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    mapBox: makeNodeComponent("mapBox"),
    sideBarBox: makeNodeComponent("sideBarBox"),
    freeBox: makeNodeComponent("freeBox"),
    checkboxLight: makeNodeComponent("checkboxLight"),
    checkboxTactilePav: makeNodeComponent("checkboxTactilePav"),
    checkboxCrossing: makeNodeComponent("checkboxCrossing"),
    checkboxPoi: makeNodeComponent("checkboxPoi"),
    checkboxNoise: makeNodeComponent("checkboxNoise"),
    checkboxTree: makeNodeComponent("checkboxTree"),
    checkboxOriginal: makeNodeComponent("checkboxOriginal"),
    // Metadata about props expected for PlasmicUser
    internalVariantProps: PlasmicUser__VariantProps,
    internalArgProps: PlasmicUser__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicUser;
/* prettier-ignore-end */
